// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	models "github.com/AlparslanKaraguney/trux-task/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CreateSmartFeature mocks base method.
func (m *MockStorage) CreateSmartFeature(feature *models.SmartFeature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSmartFeature", feature)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSmartFeature indicates an expected call of CreateSmartFeature.
func (mr *MockStorageMockRecorder) CreateSmartFeature(feature interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSmartFeature", reflect.TypeOf((*MockStorage)(nil).CreateSmartFeature), feature)
}

// CreateSmartModel mocks base method.
func (m *MockStorage) CreateSmartModel(model *models.SmartModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSmartModel", model)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSmartModel indicates an expected call of CreateSmartModel.
func (mr *MockStorageMockRecorder) CreateSmartModel(model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSmartModel", reflect.TypeOf((*MockStorage)(nil).CreateSmartModel), model)
}

// GetSmartFeature mocks base method.
func (m *MockStorage) GetSmartFeature(identifier string) (*models.SmartFeature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSmartFeature", identifier)
	ret0, _ := ret[0].(*models.SmartFeature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSmartFeature indicates an expected call of GetSmartFeature.
func (mr *MockStorageMockRecorder) GetSmartFeature(identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSmartFeature", reflect.TypeOf((*MockStorage)(nil).GetSmartFeature), identifier)
}

// GetSmartModel mocks base method.
func (m *MockStorage) GetSmartModel(identifier string) (*models.SmartModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSmartModel", identifier)
	ret0, _ := ret[0].(*models.SmartModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSmartModel indicates an expected call of GetSmartModel.
func (mr *MockStorageMockRecorder) GetSmartModel(identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSmartModel", reflect.TypeOf((*MockStorage)(nil).GetSmartModel), identifier)
}
