apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  type: LoadBalancer
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app: smart-service
