apiVersion: v1
kind: Service
metadata:
  name: health-service
spec:
  type: ClusterIP # Internal-only service
  ports:
    - name: health
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: smart-service
